name: Docker Build CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build Docker image
      run: |
        docker build . --file Dockerfile --tag imagenet-classifier:ci

    - name: Run tests
      run: |
        python test.py
